// AI Quiz Generation System Constants

export const DAILY_QUOTA_LIMITS = {
  FREE: 0,
  PREMIUM: 5,
  PREMIUM_PLUS: 15,
  LIFETIME: 999,
} as const;

export const DIFFICULTY_LEVELS = [
  {
    level: 1,
    tier: "NOVICE",
    name: "Novice",
    emoji: "🌱",
    description: "Perfect for beginners",
    baseXP: 50,
    passRate: 0.95,
    color: "#10B981",
  },
  {
    level: 2,
    tier: "BEGINNER",
    name: "Beginner",
    emoji: "📘",
    description: "Easy questions for learning",
    baseXP: 75,
    passRate: 0.88,
    color: "#3B82F6",
  },
  {
    level: 3,
    tier: "ELEMENTARY",
    name: "Elementary",
    emoji: "🔍",
    description: "Basic understanding required",
    baseXP: 100,
    passRate: 0.8,
    color: "#06B6D4",
  },
  {
    level: 4,
    tier: "INTERMEDIATE",
    name: "Intermediate",
    emoji: "🧠",
    description: "Standard difficulty level",
    baseXP: 150,
    passRate: 0.7,
    color: "#8B5CF6",
  },
  {
    level: 5,
    tier: "ADVANCED",
    name: "Advanced",
    emoji: "📜",
    description: "Challenging questions",
    baseXP: 200,
    passRate: 0.6,
    color: "#EC4899",
  },
  {
    level: 6,
    tier: "EXPERT",
    name: "Expert",
    emoji: "⚡",
    description: "For experienced learners",
    baseXP: 300,
    passRate: 0.45,
    color: "#F59E0B",
  },
  {
    level: 7,
    tier: "MASTER",
    name: "Master",
    emoji: "🧩",
    description: "Complex problem solving",
    baseXP: 450,
    passRate: 0.3,
    color: "#EF4444",
  },
  {
    level: 8,
    tier: "VIRTUOSO",
    name: "Virtuoso",
    emoji: "🎯",
    description: "Requires deep expertise",
    baseXP: 650,
    passRate: 0.2,
    color: "#DC2626",
  },
  {
    level: 9,
    tier: "LEGENDARY",
    name: "Legendary",
    emoji: "🔥",
    description: "Elite level challenges",
    baseXP: 900,
    passRate: 0.1,
    color: "#991B1B",
  },
  {
    level: 10,
    tier: "GOD_LEVEL",
    name: "God Level",
    emoji: "👑",
    description: "Ultimate mastery test",
    baseXP: 1200,
    passRate: 0.05,
    color: "#FFD700",
  },
] as const;

export const AI_PROVIDERS = [
  {
    id: "openai-gpt4o",
    name: "OpenAI",
    model: "GPT-4o",
    type: "OPENAI",
    icon: "🤖",
    description: "Most capable model, best for all subjects",
    avgTime: 20,
    costPerQuiz: 0.025,
    successRate: 0.98,
    features: ["Code support", "Math equations", "Fast generation"],
    isRecommended: true,
    isActive: true,
  },
  {
    id: "openai-gpt4o-mini",
    name: "OpenAI",
    model: "GPT-4o Mini",
    type: "OPENAI",
    icon: "🤖",
    description: "Fast and cost-effective",
    avgTime: 15,
    costPerQuiz: 0.001,
    successRate: 0.95,
    features: ["Fast", "Cost-effective", "Good quality"],
    isRecommended: false,
    isActive: true,
  },
  {
    id: "openai-gpt35-turbo",
    name: "OpenAI",
    model: "GPT-3.5 Turbo",
    type: "OPENAI",
    icon: "🤖",
    description: "Budget-friendly option",
    avgTime: 12,
    costPerQuiz: 0.0005,
    successRate: 0.92,
    features: ["Affordable", "Quick", "Reliable"],
    isRecommended: false,
    isActive: true,
  },
  {
    id: "anthropic-opus",
    name: "Anthropic",
    model: "Claude 3 Opus",
    type: "ANTHROPIC",
    icon: "🎭",
    description: "Most powerful Claude model for complex reasoning",
    avgTime: 30,
    costPerQuiz: 0.038,
    successRate: 0.99,
    features: ["Exceptional reasoning", "Image analysis", "Long context"],
    isRecommended: true,
    isActive: true,
  },
  {
    id: "anthropic-sonnet",
    name: "Anthropic",
    model: "Claude 3 Sonnet",
    type: "ANTHROPIC",
    icon: "🎭",
    description: "Balanced Claude model for detailed explanations",
    avgTime: 25,
    costPerQuiz: 0.008,
    successRate: 0.97,
    features: ["Deep reasoning", "Detailed explanations", "Context awareness"],
    isRecommended: true,
    isActive: true,
  },
  {
    id: "anthropic-haiku",
    name: "Anthropic",
    model: "Claude 3 Haiku",
    type: "ANTHROPIC",
    icon: "🎭",
    description: "Fastest Claude model for quick generation",
    avgTime: 15,
    costPerQuiz: 0.00063,
    successRate: 0.95,
    features: ["Ultra-fast", "Cost-effective", "Reliable"],
    isRecommended: false,
    isActive: true,
  },
  {
    id: "gemini-pro",
    name: "Google",
    model: "Gemini Pro",
    type: "GEMINI",
    icon: "✨",
    description: "Powerful Gemini model for diverse content",
    avgTime: 22,
    costPerQuiz: 0.00625,
    successRate: 0.96,
    features: ["Multi-modal", "Large context", "Versatile"],
    isRecommended: false,
    isActive: true,
  },
  {
    id: "gemini-flash",
    name: "Google",
    model: "Gemini Flash",
    type: "GEMINI",
    icon: "⚡",
    description: "Lightning-fast Gemini model",
    avgTime: 10,
    costPerQuiz: 0.003,
    successRate: 0.93,
    features: ["Ultra-fast", "Cheapest", "Good quality"],
    isRecommended: false,
    isActive: true,
  },
] as const;

export const POPULAR_SUBJECTS = [
  { id: "mathematics", name: "Mathematics", icon: "➕", color: "#3B82F6" },
  { id: "science", name: "Science", icon: "🔬", color: "#10B981" },
  { id: "physics", name: "Physics", icon: "⚛️", color: "#8B5CF6" },
  { id: "chemistry", name: "Chemistry", icon: "🧪", color: "#EC4899" },
  { id: "biology", name: "Biology", icon: "🧬", color: "#14B8A6" },
  { id: "history", name: "History", icon: "📜", color: "#F59E0B" },
  { id: "geography", name: "Geography", icon: "🌍", color: "#06B6D4" },
  { id: "literature", name: "Literature", icon: "📚", color: "#A855F7" },
  { id: "programming", name: "Programming", icon: "💻", color: "#EF4444" },
  { id: "languages", name: "Languages", icon: "🗣️", color: "#F97316" },
  { id: "business", name: "Business", icon: "💼", color: "#6366F1" },
  { id: "economics", name: "Economics", icon: "📊", color: "#84CC16" },
] as const;

export const GRADE_LEVELS = [
  "Elementary School",
  "Middle School",
  "High School",
  "Undergraduate",
  "Graduate",
  "Professional",
  "General Knowledge",
] as const;

export const TEMPLATE_CATEGORIES = [
  "Exam Preparation",
  "Study Guide",
  "Practice Test",
  "Quick Review",
  "Competitive Exam",
  "Certification",
] as const;

export const AI_QUIZ_ACHIEVEMENTS = {
  FIRST_AI_QUIZ: {
    key: "first_ai_quiz",
    name: "AI Pioneer",
    description: "Generate your first AI quiz",
    icon: "🤖",
    xpReward: 50,
  },
  TEN_AI_QUIZZES: {
    key: "ten_ai_quizzes",
    name: "AI Enthusiast",
    description: "Generate 10 AI quizzes",
    icon: "⚡",
    xpReward: 200,
  },
  PERFECT_SCORE_AI: {
    key: "perfect_score_ai",
    name: "Perfectionist",
    description: "Score 100% on an AI-generated quiz",
    icon: "🎯",
    xpReward: 100,
  },
  GOD_LEVEL_COMPLETE: {
    key: "god_level_complete",
    name: "Deity",
    description: "Complete a God Level quiz with 80%+",
    icon: "👑",
    xpReward: 500,
  },
  SPEED_DEMON: {
    key: "speed_demon",
    name: "Speed Demon",
    description: "Complete quiz in under 50% of time",
    icon: "⚡",
    xpReward: 150,
  },
} as const;
