export interface RankTier {
  tier: number;
  name: string;
  emoji: string;
  description: string;
  theme: string;
  colorScheme: string[];
  cardUI: string;
  badgeConcept: string;
  xpMin: number;
  xpMax: number;
}

export const RANK_TIERS: RankTier[] = [
  {
    tier: 1,
    name: 'Novara',
    emoji: '🌱',
    description: 'The humble beginning. New to the arena. Exploring the world of trivia.',
    theme: 'Minimal Starter',
    colorScheme: ['#7ecbff', '#f5faff'],
    cardUI: 'Paper texture, circuit border',
    badgeConcept: 'Flat spiral scroll with glowing dot',
    xpMin: 0,
    xpMax: 200,
  },
  {
    tier: 2,
    name: 'Mentora',
    emoji: '📘',
    description: 'The basics are forming. Learning the ways of knowledge.',
    theme: 'Student / Scholar',
    colorScheme: ['#a3d8ff', '#b0b7c3'],
    cardUI: 'Clean slate, underline animation',
    badgeConcept: 'Open scroll with question mark flare',
    xpMin: 201,
    xpMax: 800,
  },
  {
    tier: 3,
    name: 'Cognita',
    emoji: '🔍',
    description: 'Awareness grows. Accuracy starts shining.',
    theme: 'Learning Spark',
    colorScheme: ['#7fffd4', '#20b2aa'],
    cardUI: 'Slight spark effect on card edges',
    badgeConcept: '3D leaf crown with neural network lines',
    xpMin: 801,
    xpMax: 2000,
  },
  {
    tier: 4,
    name: 'Sapienta',
    emoji: '🧠',
    description: 'Wisdom awakens. Strong in logic-based rounds.',
    theme: 'Wisdom Unfolding',
    colorScheme: ['#e2c275', '#800000'],
    cardUI: 'Folded paper style, soft glows',
    badgeConcept: 'Layered scroll + floating brain aura',
    xpMin: 2001,
    xpMax: 4000,
  },
  {
    tier: 5,
    name: 'Lexora',
    emoji: '📜',
    description: 'Skilled in facts, language, and categories.',
    theme: 'Logic & Laws',
    colorScheme: ['#0a2342', '#c0c0c0'],
    cardUI: 'Card with embedded glyph symbols',
    badgeConcept: '3D scale of justice meets brain',
    xpMin: 4001,
    xpMax: 8000,
  },
  {
    tier: 6,
    name: 'Intellica',
    emoji: '⚡',
    description: 'Quick-witted. Dominating time-based duels.',
    theme: 'Futuristic Circuit',
    colorScheme: ['#00fff7', '#111112'],
    cardUI: 'Motion border, pulse glow',
    badgeConcept: '3D orb with lightning & neurons',
    xpMin: 8001,
    xpMax: 16000,
  },
  {
    tier: 7,
    name: 'Acuvera',
    emoji: '🧩',
    description: 'Precision and depth. Begins to command team matches.',
    theme: 'Precision & Aim',
    colorScheme: ['#2a3439', '#50fa7b'],
    cardUI: 'Thin outline card, zoom-in effect',
    badgeConcept: 'Stylized arrow piercing brain symbol',
    xpMin: 16001,
    xpMax: 32000,
  },
  {
    tier: 8,
    name: 'Mindara',
    emoji: '🎯',
    description: 'Battle-tested. Wins most solo challenges.',
    theme: 'Focus & Speed',
    colorScheme: ['#a259f7', '#b0b0b0'],
    cardUI: 'Glitch animation on hover',
    badgeConcept: '3D headset with flame wings',
    xpMin: 32001,
    xpMax: 65000,
  },
  {
    tier: 9,
    name: 'Neurona',
    emoji: '🌐',
    description: 'Brains synced. Regional leaderboard contender.',
    theme: 'Neural Champion',
    colorScheme: ['#00ffb3', '#ff4fa3'],
    cardUI: 'Rounded UI card with pulse map',
    badgeConcept: 'Floating network of animated synapses',
    xpMin: 65001,
    xpMax: 130000,
  },
  {
    tier: 10,
    name: 'Strategix',
    emoji: '♟️',
    description: 'Smart, composed, and tactical. Reaches top-tier challenges.',
    theme: 'Tactical IQ',
    colorScheme: ['#3f51b5', '#00bfff'],
    cardUI: 'Hex-grid background with lens effect',
    badgeConcept: 'Brain inside a transparent chess piece',
    xpMin: 130001,
    xpMax: 270000,
  },
  {
    tier: 11,
    name: 'Excellon',
    emoji: '🏆',
    description: 'Top 10% of players. Rarely makes mistakes.',
    theme: 'Elite Sharpened',
    colorScheme: ['#dc143c', '#ffd700'],
    cardUI: 'Crown-badge border, animated XP bar',
    badgeConcept: '3D trophy orb levitating with fire trail',
    xpMin: 270001,
    xpMax: 550000,
  },
  {
    tier: 12,
    name: 'Ascendrix',
    emoji: '🔥',
    description: 'Climbs elite charts. Becomes a recognizable name.',
    theme: 'The Rising Elite',
    colorScheme: ['#a259f7', '#000000'],
    cardUI: 'Particle trails on hover',
    badgeConcept: 'Animated step tower with floating glyphs',
    xpMin: 550001,
    xpMax: 1200000,
  },
  {
    tier: 13,
    name: 'Quizora',
    emoji: '✨',
    description: 'Respected in global arena. Stats, IQ, and accuracy unmatched.',
    theme: 'Mythic Master',
    colorScheme: ['#0a2342', '#ffd700'],
    cardUI: 'Quiz sparks and star highlight on card',
    badgeConcept: 'Haloed brain surrounded by stars',
    xpMin: 1200001,
    xpMax: 3000000,
  },
  {
    tier: 14,
    name: 'Ecliptix',
    emoji: '🌌',
    description: 'Enigmatic brilliance. Solves quizzes like a machine.',
    theme: 'Cosmic Brilliance',
    colorScheme: ['#000000', '#ffe600'],
    cardUI: 'Card with eclipsing border light',
    badgeConcept: 'Solar ring orbiting neuron sphere',
    xpMin: 3000001,
    xpMax: 10000000,
  },
  {
    tier: 15,
    name: 'Omniscian',
    emoji: '👑',
    description: 'GOD TIER. Holds divine command over knowledge. Only the chosen reach.',
    theme: 'God-Tier Ultimate',
    colorScheme: ['#ffd700', '#a259f7'],
    cardUI: 'Aurora glow, floating holographic stats',
    badgeConcept: '3D crown embedded in crystal neuron with celestial orbit',
    xpMin: 10000001,
    xpMax: Infinity,
  },
]; 
